namespace Morpeh.SourceGeneration.Common;

public static class Const
{
  public const string AutoGeneratedText =
    """
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    """;
}