using Morpeh.SourceGeneration.Common;

namespace Morpeh.SourceGeneration.FeatureGenerator;

public static class RegisterAttribute
{
    public const string AttributeName = "Register";
    public static readonly string AttributeFullName = AttributeName.WithAttributePostfix();

    public static readonly string AttributeText =
        $$"""
          /// <auto-generated />

          [global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = true, AllowMultiple = false)]
          internal sealed class {{AttributeFullName}} : global::System.Attribute { }
          """;
}