//HintName: WithoutAttribute.g.cs
/// <auto-generated />

[global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = true, AllowMultiple = true)]
internal sealed class WithoutAttribute : global::System.Attribute
{
	private System.Type[] _types;

	public WithoutAttribute(params System.Type[] types)
	{
		_types = types;
	}
}