namespace Morpeh.SourceGeneration.SystemGenerator;

public static class SystemInterfaces
{
    public const string InitializeInterfaceName = "IInitializeSystem";
    public const string UpdateInterfaceName = "IUpdateSystem";

    public const string InterfacesText = $$"""
       /// <auto-generated />

       public interface {{InitializeInterfaceName}}
       {
           void Start();
       }
       
       public interface {{UpdateInterfaceName}}
       {
           void Update();
       }
       """;
}