//HintName: RegisterAttribute.g.cs
/// <auto-generated />

[global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = true, AllowMultiple = false)]
internal sealed class RegisterAttribute : global::System.Attribute { }