#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using MorpehAttributes.Common;
using MorpehAttributes.Shared.SystemList;

namespace MorpehAttributes.SystemList;

[Generator]
public class SystemListGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new SystemListSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxContextReceiver is not SystemListSyntaxReceiver receiver)
        {
            return;
        }

        foreach (var kvp in receiver.Test)
        {
            var codeBuilder = new CodeBuilder();
            var systems = kvp.Value.Select(syntax => BuildAttribute(syntax, context.Compilation)).OfType<SystemInfo>().ToList();
            
            codeBuilder.AppendLine(Const.AutoGeneratedText);
            codeBuilder.AppendEmptyLine();
            
            codeBuilder.AppendLine(Const.UtilUsings);
            var namespaces = systems
                .Select(system => system.SystemListAttribute.SystemType.Namespace)
                .Distinct();
            
            foreach (var @namespace in namespaces)
            {
                codeBuilder.AppendLine($"using {@namespace};");
            }
            
            codeBuilder.AppendEmptyLine();
            
            var classSymbol = kvp.Key;
            if (!classSymbol.ContainingNamespace.IsGlobalNamespace)
            {
                codeBuilder.AppendLine(
                    $"namespace {string.Join(".", classSymbol.ContainingNamespace.ConstituentNamespaces)}"
                );
                codeBuilder.AppendOpenBraces();
            }
            
            var containingTypes = new List<INamedTypeSymbol>();
            var containingType = classSymbol.ContainingType;
            while (containingType != null)
            {
                containingTypes.Add(containingType);
                containingType = containingType.ContainingType;
            }
            
            containingTypes.Reverse();
            foreach (var type in containingTypes)
            {
                codeBuilder.AppendLine($"public partial class {type.Name}");
                codeBuilder.AppendOpenBraces();
            }
            
            codeBuilder.AppendLine($"public partial class {classSymbol.Name}");
            codeBuilder.AppendOpenBraces();
            
            // Fields
            foreach (var system in systems)
            {
                codeBuilder.AppendLine($"private {system.TypeSyntax} {system.VarName};");
            }

            AddFunction($"public {classSymbol.Name}()", system => $"{system.VarName} = new {system.TypeSyntax}();", withAttributes: false);
            AddFunction("public void OnAwake()", system => $"{system.VarName}.OnAwake();");
            
            AddFunctionWithFilter(
                headerLine: "public void OnUpdate(float deltaTime)", 
                systemLine: system => $"{system.VarName}.OnUpdate(deltaTime);",
                filter: system => system.SystemListAttribute.UpdatePhase == UpdatePhase.Update
            );
            AddFunctionWithFilter(
                headerLine: "public void OnFixedUpdate(float deltaTime)", 
                systemLine: system => $"{system.VarName}.OnUpdate(deltaTime);",
                filter: system => system.SystemListAttribute.UpdatePhase == UpdatePhase.Fixed
            );
            AddFunctionWithFilter(
                headerLine: "public void OnLateUpdate(float deltaTime)",
                systemLine: system => $"{system.VarName}.OnUpdate(deltaTime);",
                filter: system => system.SystemListAttribute.UpdatePhase == UpdatePhase.Late
            );
            
            AddFunction("public void Dispose()", system => $"{system.VarName}.Dispose();");
            
            codeBuilder.AppendCloseBraces();
            
            if (!classSymbol.ContainingNamespace.IsGlobalNamespace)
            {
                codeBuilder.AppendCloseBraces();
            }

            var classSource = codeBuilder.ToString();
            context.AddSource($"{classSymbol.Name}.g.cs", SourceText.From(classSource, Encoding.UTF8));

            void AddFunction(string headerLine, Func<SystemInfo, string> systemLine, bool withAttributes = true)
            {
                AddFunctionWithFilter(headerLine, systemLine, _ => true, withAttributes);
            }
            
            void AddFunctionWithFilter(
                string headerLine,
                Func<SystemInfo, string> systemLine,
                Func<SystemInfo, bool> filter,
                bool withAttributes = true
            )
            {
                codeBuilder.AppendEmptyLine();
                if (withAttributes)
                {
                    codeBuilder.AppendLine(Const.UtilAttributes);
                }
                codeBuilder.AppendLine(headerLine);
                codeBuilder.AppendOpenBraces();
                foreach (var system in systems.Where(filter))
                {
                    codeBuilder.AppendLine(systemLine(system));
                }
                codeBuilder.AppendCloseBraces();
            }
        }
    }

    private static SystemInfo? BuildAttribute(AttributeSyntax attributeSyntax, Compilation compilation)
    {
        var attribute = attributeSyntax.GetAttribute(compilation)?.MapToType<SystemListAttribute>();
        
        var args = attributeSyntax.ArgumentList?.Arguments.ToList();
        var typeAttributeArgument = args?[0];
        if (typeAttributeArgument?.Expression is not TypeOfExpressionSyntax typeOfExpression)
        {
            return null;
        }

        return new SystemInfo(typeOfExpression.Type, attribute);
    }
}