namespace Morpeh.SourceGeneration.FeatureRunnerGenerator;

public static class FeatureRunnerInterface
{
    public const string FeatureRunnerInterfaceName = "IFeatureRunner";
    public const string InterfaceText = $$"""
       /// <auto-generated />

       public interface {{FeatureRunnerInterfaceName}} { }
       """;
}