using Morpeh.SourceGeneration.Common;

namespace Morpeh.SourceGeneration.FeatureRunnerGenerator;

public static class WithWorldAttribute
{
    public const string AttributeName = "WithWorld";
    public static readonly string AttributeFullName = AttributeName.WithAttributePostfix();

    public static readonly string AttributeText =
        $$"""
          /// <auto-generated />

          [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = true, AllowMultiple = false)]
          internal sealed class {{AttributeFullName}} : global::System.Attribute { }
          """;
}



