//HintName: WithWorldAttribute.g.cs
/// <auto-generated />

[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = true, AllowMultiple = false)]
internal sealed class WithWorldAttribute : global::System.Attribute { }